### ISSUE TITLE
UC008 - Consultar DNS

### ISSUE THREAD

**Issue by henmerlin** [pjefika/acs2#28]

**Comment by henmerlin** [comment]
**Aguardando caso de teste**

**Comment by Agibert** [comment]
apresenta a exceção abaixo para devices GUID 74021 e 89013:
com.motive.synchdeviceopsimpl.synchdeviceoperationsnbiservice.DeviceOperationException: status=1, operationId=171649, faultKey=cwmp.fault.2, faultString=Cannot execute GetParameterValues

**Comment by henmerlin** [comment]
com.motive.synchdeviceopsimpl.synchdeviceoperationsnbiservice.DeviceOperationException: status=1, operationId=176236, faultKey=cwmp.fault.2, faultString=O CPE não suporta o(s) parâmetro(s) solicitados.
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
