### ISSUE TITLE
UC014 - Gerenciar DMZ

### ISSUE THREAD

**Issue by henmerlin** [pjefika/acs2#34]

**Comment by henmerlin** [comment]
> O CPE não suporta o(s) parâmetro(s) solicitados.
**Buscar equipamento para homologação.**

**Comment by Agibert** [comment]
Apresenta exceção abaixo para o device GUID 74021:
com.motive.synchdeviceopsimpl.synchdeviceoperationsnbiservice.DeviceOperationException: status=1, operationId=171737, faultKey=cwmp.fault.2, faultString=Cannot execute GetParameterValues

**Comment by Agibert** [comment]
mesma exceção para o device GUID 89013

**Comment by henmerlin** [comment]
com.motive.synchdeviceopsimpl.synchdeviceoperationsnbiservice.DeviceOperationException: status=1, operationId=176238, faultKey=cwmp.fault.2, faultString=O CPE não suporta o(s) parâmetro(s) solicitados.
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
